Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig, ax = plt.subplots()
ax.plot(np.log10(pc_curve_ibip.pc), pc_curve_ibip.snwp, 'g-', linewidth=2, label='IBIP')
ax.step(np.array(np.log10(pc_curve_mio.pc)), pc_curve_mio.snwp, 'r--', where='post', markersize=20, linewidth=3, alpha=0.6, label='MIO')
plt.xlabel('log(Capillary Pressure [Pa])')
plt.ylabel('Non-wetting Phase Saturation')
plt.legend()
ax.xaxis.grid(True, which='both')
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[10], line 3[0m
[1;32m      1[0m fig, ax [38;5;241m=[39m plt[38;5;241m.[39msubplots()
[1;32m      2[0m ax[38;5;241m.[39mplot(np[38;5;241m.[39mlog10(pc_curve_ibip[38;5;241m.[39mpc), pc_curve_ibip[38;5;241m.[39msnwp, [38;5;124m'[39m[38;5;124mg-[39m[38;5;124m'[39m, linewidth[38;5;241m=[39m[38;5;241m2[39m, label[38;5;241m=[39m[38;5;124m'[39m[38;5;124mIBIP[39m[38;5;124m'[39m)
[0;32m----> 3[0m ax[38;5;241m.[39mstep(np[38;5;241m.[39marray(np[38;5;241m.[39mlog10([43mpc_curve_mio[49m[38;5;241m.[39mpc)), pc_curve_mio[38;5;241m.[39msnwp, [38;5;124m'[39m[38;5;124mr--[39m[38;5;124m'[39m, where[38;5;241m=[39m[38;5;124m'[39m[38;5;124mpost[39m[38;5;124m'[39m, markersize[38;5;241m=[39m[38;5;241m20[39m, linewidth[38;5;241m=[39m[38;5;241m3[39m, alpha[38;5;241m=[39m[38;5;241m0.6[39m, label[38;5;241m=[39m[38;5;124m'[39m[38;5;124mMIO[39m[38;5;124m'[39m)
[1;32m      4[0m plt[38;5;241m.[39mxlabel([38;5;124m'[39m[38;5;124mlog(Capillary Pressure [Pa])[39m[38;5;124m'[39m)
[1;32m      5[0m plt[38;5;241m.[39mylabel([38;5;124m'[39m[38;5;124mNon-wetting Phase Saturation[39m[38;5;124m'[39m)

[0;31mNameError[0m: name 'pc_curve_mio' is not defined

